// ps1xRecomp — PS1 Static Recompiler
// Translates MIPS I instructions to C++ code (1:1 literal translation)

#include <cstdio>
#include <filesystem>
#include <fmt/format.h>
#include <fstream>
#include <map>
#include <ps1recomp/elf_parser.h>
#include <ps1recomp/instruction_emitter.h>
#include <ps1recomp/mips_decoder.h>
#include <string>
#include <toml.hpp>
#include <vector>

using namespace ps1recomp;

int main(int argc, char *argv[]) {
  if (argc < 2) {
    fmt::print("Usage: ps1xRecomp <config.toml> [output_file.cpp]\n");
    return 1;
  }

  std::string config_path = argv[1];
  std::string output_path = (argc >= 3) ? argv[2] : "recompiled_out.cpp";

  try {
    const auto config = toml::parse(config_path);

    // binary path is relative to the config file ideally, but for now we assume
    // it builds from project root
    std::string elf_path = toml::find<std::string>(config, "binary", "path");
    uint32_t entry_point = std::stoul(
        toml::find<std::string>(config, "binary", "entry_point"), nullptr, 16);

    fmt::print("Loading binary: {}\n", elf_path);
    ps1recomp::ElfParser parser;
    if (!parser.load(elf_path)) {
      fmt::print(stderr, "Failed to load ELF: {}\n", parser.getError());
      return 1;
    }

    std::string result_cpp = "// Generated by ps1xRecomp\n";
    result_cpp += "#include <cstdint>\n";
    result_cpp += "#include <runtime/ps1_runtime_macros.h>\n";
    result_cpp += "#include <runtime/cpu_context.h>\n";
    result_cpp += "#include <runtime/gte.h>\n\n";

    const auto &functions =
        toml::find<std::vector<toml::value>>(config, "functions");

    std::map<uint32_t, std::string> addr_to_name;
    std::vector<uint32_t> known_funcs;
    for (const auto &func : functions) {
      std::string name = toml::find<std::string>(func, "name");
      if (name == "main")
        name = "func_main";
      for (char &c : name)
        if (c == '.')
          c = '_';
      uint32_t addr =
          std::stoul(toml::find<std::string>(func, "address"), nullptr, 16);
      known_funcs.push_back(addr);
      addr_to_name[addr] = name;
      result_cpp +=
          fmt::format("void {}(uint8_t* rdram, recomp_context* ctx);\n", name);
    }

    // Also include stubs in known functions if they exist
    if (config.contains("stubs")) {
      const auto &stubs = toml::find<std::vector<toml::value>>(config, "stubs");
      for (const auto &s : stubs) {
        std::string name = toml::find<std::string>(s, "name");
        if (name == "main")
          name = "func_main";
        for (char &c : name)
          if (c == '.')
            c = '_';
        uint32_t addr =
            std::stoul(toml::find<std::string>(s, "address"), nullptr, 16);
        known_funcs.push_back(addr);
        addr_to_name[addr] = name;
        result_cpp += fmt::format(
            "void {}(uint8_t* rdram, recomp_context* ctx);\n", name);
      }
    }

    result_cpp += "\n";

    InstructionEmitter emitter;
    emitter.setFuncResolver([&addr_to_name](uint32_t addr) {
      if (addr_to_name.count(addr))
        return addr_to_name[addr];
      return fmt::format("func_{:08X}", addr);
    });

    fmt::print("Recompiling {} functions...\n", functions.size());

    for (const auto &func : functions) {
      std::string name = toml::find<std::string>(func, "name");
      if (name == "main")
        name = "func_main";
      for (char &c : name)
        if (c == '.')
          c = '_';
      uint32_t addr =
          std::stoul(toml::find<std::string>(func, "address"), nullptr, 16);
      uint32_t size = toml::find<int64_t>(func, "size");

      // Extract instructions
      auto *section = parser.findSectionByAddress(addr);
      if (!section || section->type != SectionType::Text)
        continue;

      uint32_t offset = addr - section->vaddr;
      uint32_t num_instrs = size / 4;

      RecompFunction rfunc;
      rfunc.name = name;
      rfunc.address = addr;
      rfunc.size = size;
      rfunc.instructions.resize(num_instrs);
      rfunc.isLabelTarget.resize(num_instrs, false);

      for (uint32_t i = 0; i < num_instrs; ++i) {
        const uint8_t *ptr = section->data + offset + (i * 4);
        rfunc.instructions[i] =
            ptr[0] | (ptr[1] << 8) | (ptr[2] << 16) | (ptr[3] << 24);

        Instruction inst = MipsDecoder::decode(rfunc.instructions[i]);
        if (inst.category == InstrCategory::Branch) {
          uint32_t pc = addr + (i * 4);
          uint32_t target = inst.branchTarget(pc);
          if (target >= addr && target < addr + size) {
            uint32_t target_idx = (target - addr) / 4;
            if (target_idx < num_instrs)
              rfunc.isLabelTarget[target_idx] = true;
          }
        } else if (inst.category == InstrCategory::Jump &&
                   (inst.id == InstrId::J || inst.id == InstrId::JAL)) {
          uint32_t pc = addr + (i * 4);
          uint32_t target = inst.jumpTarget(pc);
          if (target >= addr && target < addr + size) {
            uint32_t target_idx = (target - addr) / 4;
            if (target_idx < num_instrs)
              rfunc.isLabelTarget[target_idx] = true;
          }
          if (inst.id == InstrId::JAL) {
            bool found = false;
            for (auto k : known_funcs) {
              if (k == target) {
                found = true;
                break;
              }
            }
            if (!found) {
              known_funcs.push_back(target);
              result_cpp += fmt::format(
                  "void func_{:08X}(uint8_t* rdram, recomp_context* ctx) {{ /* "
                  "STUB generated by JAL */ }}\n",
                  target);
            }
          }
        }
      }

      result_cpp += emitter.emitFunction(rfunc);
      result_cpp += "\n";
    }

    // Emit stub implementations for PsyQ stubs!
    if (config.contains("stubs")) {
      const auto &stubs = toml::find<std::vector<toml::value>>(config, "stubs");
      for (const auto &s : stubs) {
        std::string name = toml::find<std::string>(s, "name");
        for (char &c : name)
          if (c == '.')
            c = '_';
        result_cpp += fmt::format("void {}(uint8_t* rdram, recomp_context* "
                                  "ctx) {{ /* PsyQ Stub */ }}\n",
                                  name);
      }
    }

    std::ofstream out(output_path);
    if (!out) {
      fmt::print(stderr, "Failed to write output to {}\n", output_path);
      return 1;
    }
    out << result_cpp;
    fmt::print("Success! Emitted Recompiled source to: {}\n", output_path);

  } catch (const std::exception &e) {
    fmt::print(stderr, "Error parsing config: {}\n", e.what());
    return 1;
  }

  return 0;
}
