// ps1xRuntime — PS1 Hardware Simulation Runtime
// Full system integration: CPU, GPU, SPU, CD-ROM, DMA, Input, MDEC, Timers
// Game code runs in separate thread; main thread handles SDL events + rendering

#include "runtime/ps1_runtime_macros.h"
#include <SDL2/SDL.h>
#include <atomic>
#include <chrono>
#include <cstring>
#include <exception>
#include <filesystem>
#include <fmt/format.h>
#include <iostream>
#include <ps1recomp/elf_parser.h>
#include <runtime/bios/bios.h>
#include <runtime/psyq/psyq_hle.h>
#include <runtime/cdrom/cdrom_controller.h>
#include <runtime/cdrom/virtual_fs.h>
#include <runtime/cpu_context.h>
#include <runtime/dma/dma.h>
#include <runtime/gpu/gpu.h>
#include <runtime/gpu/renderer_opengl.h>
#include <runtime/input/input.h>
#include <runtime/mdec/mdec.h>
#include <runtime/memory.h>
#include <runtime/spu/spu.h>
#include <runtime/timers/timers.h>
#include <string>
#include <thread>
#include <toml.hpp>
#include <vector>

// ─── SDL2 Audio Callback ────────────────────────────────
static ps1::spu::SPU *g_spu = nullptr;

// Forward declaration — generated by ps1xRecomp in recompiled_out.cpp
extern void recomp_init_dispatch_table();
using recomp_func_t = void (*)(uint8_t *, recomp_context *);
extern void recomp_register_override(uint32_t addr, recomp_func_t fn);

static void audioCallback(void * /*userdata*/, uint8_t *stream, int len) {
  if (!g_spu) {
    std::memset(stream, 0, len);
    return;
  }
  uint32_t numSamples = len / (2 * sizeof(int16_t)); // stereo S16
  g_spu->generateSamples(reinterpret_cast<int16_t *>(stream), numSamples);
}

// ─── SDL2 Key Mapping ───────────────────────────────────
static void mapKeyToButton(SDL_Keycode key, ps1::input::InputController &input,
                           bool pressed) {
  using namespace ps1::input;
  uint16_t btn = 0;
  switch (key) {
  case SDLK_UP:
    btn = BTN_UP;
    break;
  case SDLK_DOWN:
    btn = BTN_DOWN;
    break;
  case SDLK_LEFT:
    btn = BTN_LEFT;
    break;
  case SDLK_RIGHT:
    btn = BTN_RIGHT;
    break;
  case SDLK_z:
    btn = BTN_CROSS;
    break;
  case SDLK_x:
    btn = BTN_CIRCLE;
    break;
  case SDLK_a:
    btn = BTN_SQUARE;
    break;
  case SDLK_s:
    btn = BTN_TRIANGLE;
    break;
  case SDLK_q:
    btn = BTN_L1;
    break;
  case SDLK_w:
    btn = BTN_R1;
    break;
  case SDLK_e:
    btn = BTN_L2;
    break;
  case SDLK_r:
    btn = BTN_R2;
    break;
  case SDLK_RETURN:
    btn = BTN_START;
    break;
  case SDLK_RSHIFT:
  case SDLK_BACKSPACE:
    btn = BTN_SELECT;
    break;
  default:
    return;
  }
  if (pressed)
    input.press(btn, 0);
  else
    input.release(btn, 0);
}

// ─── Constants ──────────────────────────────────────────
static constexpr uint32_t CPU_CLOCK = 33868800;              // 33.8688 MHz
static constexpr uint32_t CYCLES_PER_FRAME = CPU_CLOCK / 60; // ~564480
static constexpr uint32_t CYCLES_PER_SCANLINE = 3413; // ~3413 cycles per hblank
static constexpr uint32_t SCANLINES_PER_FRAME = 263;  // NTSC

int main(int argc, char *argv[]) {
  if (argc < 2) {
    std::cerr << "Usage: ps1xRuntime <ps1_elf_or_iso> [disc_image] [--config "
                 "game.toml]\n"
              << "       ps1xRuntime --config game.toml\n";
    return 1;
  }

  // Parse arguments: support --config flag anywhere
  std::string input_path;
  std::string explicit_disc_path;
  std::string config_path;
  for (int i = 1; i < argc; i++) {
    if (std::string(argv[i]) == "--config" && i + 1 < argc) {
      config_path = argv[++i];
    } else if (input_path.empty()) {
      input_path = argv[i];
    } else if (explicit_disc_path.empty()) {
      explicit_disc_path = argv[i];
    }
  }

  // If only a TOML config is provided, read paths from it
  if (input_path.empty() && !config_path.empty()) {
    try {
      auto cfg = toml::parse(config_path);
      if (cfg.contains("disc")) {
        auto &disc = toml::find(cfg, "disc");
        if (disc.contains("exe_path"))
          input_path = toml::find<std::string>(disc, "exe_path");
        if (disc.contains("cue_path"))
          explicit_disc_path = toml::find<std::string>(disc, "cue_path");
      }
    } catch (const std::exception &e) {
      fmt::print(stderr, "Failed to parse config: {}\n", e.what());
      return 1;
    }
  }
  if (input_path.empty()) {
    std::cerr << "No ELF/EXE path provided (via argument or --config)\n";
    return 1;
  }
  fmt::print("ps1xRuntime — PS1 Hardware Simulation (Full Integration)\n");

  // ─── Initialize all hardware subsystems ────────────

  // Core
  ps1::Memory memory;
  ps1::gpu::GPU gpu;
  ps1::spu::SPU spu;
  ps1::DMA dma;
  ps1::InterruptController irqCtrl;
  ps1::Timers timers;
  ps1::input::InputController input;
  ps1::mdec::MDEC mdec;
  ps1::cdrom::CdromController cdromCtrl;
  ps1::cdrom::VirtualFs fs;

  // Wire Memory I/O routing
  memory.setGPU(&gpu);
  memory.setSPU(&spu);
  memory.setDMA(&dma);
  memory.setCDROM(&cdromCtrl);
  memory.setInput(&input);
  memory.setMDEC(&mdec);
  memory.setTimers(&timers);
  memory.setInterruptController(&irqCtrl);

  // Wire DMA to devices
  dma.setMemory(&memory);
  dma.setGPU(&gpu);
  dma.setSPU(&spu);
  dma.setCDROM(&cdromCtrl);
  dma.setMDEC(&mdec);

  // Wire CDROM to VirtualFS
  cdromCtrl.attachVirtualFs(&fs);

  // Wire XA-ADPCM from CDROM → SPU
  cdromCtrl.setXaCallback([&spu](const int16_t *samples, uint32_t count) {
    spu.pushXaSamples(samples, count);
  });

  // CPU Context
  recomp_context ctx;
  ctx.reset();
  ctx.mem = &memory;
  // Initialize Stack Pointer ($sp / r29) to top of 2MB Main RAM (KSEG0)
  ctx.r[29] = 0x801FFFF0;

  // BIOS
  ps1::bios::Bios bios(ctx, fs, memory);
  ctx.bios = &bios;
  bios.setGPU(&gpu);
  bios.setInputController(&input);
  bios.setCdromController(&cdromCtrl);

  // ── Per-game PsyQ BSS address configuration ──
  // Priority: TOML config file > environment variables > defaults (0)
  {
    ps1::bios::Bios::PsyqAddresses addrs; // all default to 0

    // 1. Load from TOML config if provided
    if (!config_path.empty()) {
      try {
        auto cfg = toml::parse(config_path);
        if (cfg.contains("psyq_addresses")) {
          auto &pa = toml::find(cfg, "psyq_addresses");
          auto readToml = [&](const char *key, uint32_t &out) {
            if (pa.contains(key)) {
              auto val = toml::find(pa, key);
              if (val.is_integer()) {
                out = static_cast<uint32_t>(val.as_integer());
              }
              fmt::print("[CONFIG] {} = 0x{:08X} (from TOML)\n", key, out);
            }
          };
          readToml("vsync_counter", addrs.vblankCounter);
          readToml("cd_sync_byte", addrs.cdSyncByte);
          readToml("cd_ready_byte", addrs.cdReadyByte);
          readToml("cd_remaining", addrs.cdRemaining);
          readToml("cd_dest_ptr", addrs.cdDestPtr);
          readToml("cd_word_count", addrs.cdWordCount);
          readToml("cd_data_cb", addrs.cdDataCb);
          readToml("cd_notify_cb", addrs.cdNotifyCb);
          readToml("cd_status_hw", addrs.cdStatusHw);
          readToml("gpu_swap_cb", addrs.gpuSwapCb);
          readToml("gpu_drawsync_base", addrs.gpuDrawSyncBase);
          readToml("gpu_drawsync_count", addrs.gpuDrawSyncCount);
          readToml("gpu_drawsync_index_addr", addrs.gpuDrawSyncIndexAddr);
        }
      } catch (const std::exception &e) {
        fmt::print(stderr,
                   "[WARN] Failed to read psyq_addresses from config: {}\n",
                   e.what());
      }
    }

    // 2. Environment variables can override TOML values
    auto readEnvHex = [](const char *name, uint32_t &out) {
      const char *val = std::getenv(name);
      if (val) {
        out = std::strtoul(val, nullptr, 0);
        fmt::print("[CONFIG] {} = 0x{:08X} (from env)\n", name, out);
      }
    };
    readEnvHex("PSYQ_VSYNC_COUNTER", addrs.vblankCounter);
    readEnvHex("PSYQ_CD_SYNC_BYTE", addrs.cdSyncByte);
    readEnvHex("PSYQ_CD_READY_BYTE", addrs.cdReadyByte);
    readEnvHex("PSYQ_CD_REMAINING", addrs.cdRemaining);
    readEnvHex("PSYQ_CD_DEST_PTR", addrs.cdDestPtr);
    readEnvHex("PSYQ_CD_WORD_COUNT", addrs.cdWordCount);
    readEnvHex("PSYQ_CD_DATA_CB", addrs.cdDataCb);
    readEnvHex("PSYQ_CD_NOTIFY_CB", addrs.cdNotifyCb);
    readEnvHex("PSYQ_CD_STATUS_HW", addrs.cdStatusHw);
    readEnvHex("PSYQ_GPU_SWAP_CB", addrs.gpuSwapCb);
    readEnvHex("PSYQ_GPU_DRAWSYNC_BASE", addrs.gpuDrawSyncBase);
    readEnvHex("PSYQ_GPU_DRAWSYNC_COUNT", addrs.gpuDrawSyncCount);
    readEnvHex("PSYQ_GPU_DRAWSYNC_INDEX_ADDR", addrs.gpuDrawSyncIndexAddr);

    // 3. Warn if critical addresses are not configured
    if (addrs.vblankCounter == 0)
      fmt::print(
          stderr,
          "[WARN] vsync_counter not set — VSync polling will not work\n");
    if (addrs.cdSyncByte == 0 || addrs.cdReadyByte == 0)
      fmt::print(stderr, "[WARN] cd_sync_byte / cd_ready_byte not set — CD "
                         "commands may hang\n");
    if (addrs.gpuDrawSyncBase == 0)
      fmt::print(
          stderr,
          "[WARN] gpu_drawsync_base not set — DrawSync polling will block\n");

    bios.setPsyqAddresses(addrs);

    // Also configure the psyq_hle layer so that named PsyQ stubs
    // (VSync, DrawSync, etc.) have the correct per-game addresses.
    ps1::psyq::HleConfig hleCfg;
    hleCfg.vblankCounter    = addrs.vblankCounter;
    hleCfg.drawSyncBase     = addrs.gpuDrawSyncBase;
    hleCfg.drawSyncIndexAddr = addrs.gpuDrawSyncIndexAddr;
    hleCfg.drawSyncCount    = addrs.gpuDrawSyncCount;
    hleCfg.drainCallbacks   = [&bios]() { bios.drainPendingCallbacks(); };
    ps1::psyq::configure(hleCfg);

    fmt::print("[CONFIG] PsyQ addresses configured\n");
  }

  // Wire CDROM interrupt callback → BIOS event system
  // This fires IMMEDIATELY when a CDROM command completes (inside tick()),
  // before the game thread can read/acknowledge the interrupt hardware flag.
  cdromCtrl.setInterruptCallback(
      [&bios](uint8_t intType) { bios.triggerCdromEvent(intType); });

  // ─── Initialize SDL2 ──────────────────────────────

  if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_GAMECONTROLLER) < 0) {
    fmt::print(stderr, "SDL_Init failed: {}\n", SDL_GetError());
    return 1;
  }

  // Initialize renderer (creates window + OpenGL context)
  ps1::gpu::RendererOpenGL renderer(gpu);
  if (!renderer.init("ps1xRecomp Full System")) {
    fmt::print(stderr, "Failed to initialize OpenGL renderer!\n");
    SDL_Quit();
    return 1;
  }

  // ─── SDL2 Audio ───────────────────────────────────
  g_spu = &spu;
  SDL_AudioSpec desired{}, obtained{};
  desired.freq = 44100;
  desired.format = AUDIO_S16SYS;
  desired.channels = 2;
  desired.samples = 1024;
  desired.callback = audioCallback;

  SDL_AudioDeviceID audioDevice =
      SDL_OpenAudioDevice(nullptr, 0, &desired, &obtained, 0);
  if (audioDevice > 0) {
    SDL_PauseAudioDevice(audioDevice, 0); // Start playback
    fmt::print("[Audio] SDL2 audio: {}Hz, {} ch, {} samples/buffer\n",
               obtained.freq, obtained.channels, obtained.samples);
  } else {
    fmt::print(stderr, "[Audio] Warning: could not open audio: {}\n",
               SDL_GetError());
  }

  // ─── SDL2 GameController ──────────────────────────
  SDL_GameController *gamepad = nullptr;
  for (int i = 0; i < SDL_NumJoysticks(); i++) {
    if (SDL_IsGameController(i)) {
      gamepad = SDL_GameControllerOpen(i);
      if (gamepad) {
        fmt::print("[Input] GameController: {}\n",
                   SDL_GameControllerName(gamepad));
        break;
      }
    }
  }

  // ─── Load ELF or ISO ──────────────────────────────

  ps1recomp::ElfParser parser;
  if (!parser.load(input_path)) {
    fmt::print(stderr, "Failed to load ELF: {}\n", parser.getError());
    renderer.destroy();
    SDL_Quit();
    return 1;
  }

  // Auto-load corresponding Disc Image if running a extracted .boot.exe
  if (!explicit_disc_path.empty()) {
    // Disc image was explicitly provided as first argument
    if (fs.loadDisc(explicit_disc_path)) {
      fmt::print("[CDROM] Mounted disc image: {}\n", explicit_disc_path);
    } else {
      fmt::print(stderr, "[CDROM] WARNING: Could not mount disc image: {}\n",
                 explicit_disc_path);
    }
  } else {
    std::string disc_path = input_path;
    if (disc_path.ends_with(".boot.exe")) {
      disc_path =
          disc_path.substr(0, disc_path.length() - 9); // strip ".boot.exe"
      if (fs.loadDisc(disc_path)) {
        fmt::print("[CDROM] Automatically mounted disc image: {}\n", disc_path);
      } else {
        fmt::print(
            stderr,
            "[CDROM] WARNING: Could not mount corresponding disc image: {}\n",
            disc_path);
      }
    } else if (disc_path.ends_with(".bin") || disc_path.ends_with(".cue")) {
      if (fs.loadDisc(disc_path)) {
        fmt::print("[CDROM] Mounted disc image: {}\n", disc_path);
      }
    }
  }

  auto sections = parser.getSections();
  int loaded_sections = 0;
  for (const auto &sec : sections) {
    if ((sec.type == ps1recomp::SectionType::Text ||
         sec.type == ps1recomp::SectionType::Data) &&
        sec.data != nullptr) {
      uint32_t phys = ps1::Memory::toPhysical(sec.vaddr);
      if (phys < ps1::Memory::RAM_SIZE) {
        std::memcpy(memory.ramPtr() + phys, sec.data, sec.size);
        loaded_sections++;
      }
    }
  }
  fmt::print("Loaded {} sections into PS1 memory.\n", loaded_sections);

  // ─── Main Emulation Loop ──────────────────────────
  // Game code runs in a separate thread (it never returns).
  // Main thread handles SDL events + hardware ticking + rendering.

  uint32_t entryPoint = parser.getEntryPoint();
  fmt::print("Starting emulation... Entry Point: 0x{:08X}\n", entryPoint);
  std::atomic<bool> gameRunning{true};
  std::atomic<bool> gameFinished{false};
  uint64_t frameCount = 0;

  // Initialize dispatch table before starting the game
  recomp_init_dispatch_table();
  fmt::print("[Dispatch] Table initialized.\n");

  // ─── VBlank ticker thread ─────────────────────────────
  // The game spins polling the vblank counter (0x801CF2CC).  The main SDL
  // loop only fires at ~60fps but the game thread runs at full CPU speed, so
  // thousands of VSync calls time out before the SDL loop fires even once.
  // A dedicated 60Hz ticker thread writes to the vblank counter independently
  // of SDL rendering, ensuring the counter advances at the right rate and the
  // game's VSync loop exits quickly.
  std::thread vblankThread([&]() {
    using namespace std::chrono;
    const auto period = microseconds(16667); // ~60 Hz
    auto next = steady_clock::now() + period;
    while (!gameFinished.load(std::memory_order_acquire)) {
      std::this_thread::sleep_until(next);
      next += period;
      bios.triggerVBlankEvent();
      gpu.snapshotDisplayBuffer();
      bios.updatePadBuffers();
    }
  });

  // Launch game thread
  std::thread gameThread([&]() {
    try {
      ctx.pc = entryPoint;
      recomp_dispatch(memory.ramPtr(), &ctx, entryPoint);
    } catch (const ps1::CpuException &e) {
      fmt::print("[Game] CPU Exception {} at PC=0x{:08X}\n",
                 static_cast<uint32_t>(e.cause), ctx.pc);
    } catch (const std::exception &e) {
      fmt::print("[Game] Exception: {}\n", e.what());
    } catch (...) {
      fmt::print("[Game] Unknown exception\n");
    }
    gameFinished.store(true, std::memory_order_release);
  });

  bool running = true;
  while (running) {
    // ── 1. Poll SDL2 Events ────────────────────────
    SDL_Event event;
    while (SDL_PollEvent(&event)) {
      switch (event.type) {
      case SDL_QUIT:
        running = false;
        break;
      case SDL_KEYDOWN:
        if (event.key.keysym.sym == SDLK_ESCAPE) {
          running = false;
        } else {
          mapKeyToButton(event.key.keysym.sym, input, true);
        }
        break;
      case SDL_KEYUP:
        mapKeyToButton(event.key.keysym.sym, input, false);
        break;
      }
    }

    // ── 2. Tick Hardware (per frame) ────────────────
    // CDROM state machine
    cdromCtrl.tick(CYCLES_PER_FRAME);

    // Timers (263 scanlines per NTSC frame)
    uint32_t timerIrqs = 0;
    for (uint32_t scanline = 0; scanline < SCANLINES_PER_FRAME; scanline++) {
      timerIrqs |= timers.tick(CYCLES_PER_SCANLINE, true, false);
    }

    // Timer IRQs
    if (timerIrqs & ps1::IRQ_TMR0)
      irqCtrl.raiseInterrupt(ps1::IRQ_TMR0);
    if (timerIrqs & ps1::IRQ_TMR1)
      irqCtrl.raiseInterrupt(ps1::IRQ_TMR1);
    if (timerIrqs & ps1::IRQ_TMR2)
      irqCtrl.raiseInterrupt(ps1::IRQ_TMR2);

    // VBlank IRQ (once per frame)
    irqCtrl.raiseInterrupt(ps1::IRQ_VBLANK);

    // VBlank events (triggerVBlankEvent, snapshotDisplayBuffer, updatePadBuffers)
    // are now fired by the dedicated vblankThread above at a steady 60Hz,
    // so they run independently of the SDL render loop speed.

    // Other IRQs
    if (cdromCtrl.hasInterrupt()) {
      irqCtrl.raiseInterrupt(ps1::IRQ_CDROM);
      // Event triggering is now handled by the interrupt callback
      // (fired inline from pushResponse), so we only raise the HW IRQ here.
    }
    if (dma.hasInterrupt())
      irqCtrl.raiseInterrupt(ps1::IRQ_DMA);
    if (input.hasInterrupt()) {
      irqCtrl.raiseInterrupt(ps1::IRQ_PAD_MC);
      input.clearInterrupt();
    }
    if (spu.hasIrq()) {
      irqCtrl.raiseInterrupt(ps1::IRQ_SPU);
      spu.clearIrq();
    }

    // ── 3. Render ───────────────────────────────────
    if (!renderer.processEvents()) {
      running = false;
      continue;
    }
    renderer.renderFrame();

    frameCount++;

    // Status every 5 seconds
    if (frameCount % 300 == 0) {
      fmt::print("[Frame {}] I_STAT=0x{:04X} I_MASK=0x{:04X}\n", frameCount,
                 irqCtrl.readIStat(), irqCtrl.readIMask());
    }

    // One-shot display state + VRAM dump at frame 200
    if (frameCount == 200) {
      uint32_t stat = gpu.readGPUSTAT();
      uint32_t dispX, dispY;
      gpu.getDisplayArea(dispX, dispY);
      uint32_t rx1, rx2, ry1, ry2;
      gpu.getDisplayRange(rx1, rx2, ry1, ry2);
      fmt::print("[DEBUG] Frame {}: GPUSTAT=0x{:08X} displayEnabled={} "
                 "dispArea=({},{}) dispRange=({},{},{},{}) "
                 "hres_bits={}\n",
                 frameCount, stat, gpu.isDisplayEnabled(), dispX, dispY, rx1,
                 rx2, ry1, ry2, (stat >> 17) & 3);
      // Dump VRAM to PPM
      const auto *vram = gpu.getDisplayVRAM();
      FILE *f = fopen("/tmp/vram_frame200.ppm", "wb");
      if (f) {
        fprintf(f, "P6\n1024 512\n255\n");
        for (int i = 0; i < 1024 * 512; i++) {
          uint16_t c = vram[i].raw;
          uint8_t r = (c & 0x1F) << 3;
          uint8_t g = ((c >> 5) & 0x1F) << 3;
          uint8_t b = ((c >> 10) & 0x1F) << 3;
          fwrite(&r, 1, 1, f);
          fwrite(&g, 1, 1, f);
          fwrite(&b, 1, 1, f);
        }
        fclose(f);
        fmt::print("[DEBUG] VRAM dumped to /tmp/vram_frame200.ppm\n");
      }
    }

    // Check if game thread ended
    if (gameFinished.load(std::memory_order_acquire)) {
      fmt::print("[Main] Game thread finished at frame {}\n", frameCount);
      running = false;
    }

    // Frame pacing: SDL_GL_SetSwapInterval(1) provides VSync-based pacing
    // via the blocking SDL_GL_SwapWindow call in renderFrame().
    // No additional SDL_Delay needed — it would double the frame time.
  }

  // ─── Final VRAM dump ──────────────────────────────
  {
    const auto *vram = gpu.getVRAM();
    FILE *f = fopen("/tmp/vram_final.ppm", "wb");
    if (f) {
      fprintf(f, "P6\n1024 512\n255\n");
      for (int i = 0; i < 1024 * 512; i++) {
        uint16_t c = vram[i].raw;
        uint8_t r = (c & 0x1F) << 3;
        uint8_t g = ((c >> 5) & 0x1F) << 3;
        uint8_t b = ((c >> 10) & 0x1F) << 3;
        fwrite(&r, 1, 1, f);
        fwrite(&g, 1, 1, f);
        fwrite(&b, 1, 1, f);
      }
      fclose(f);
      fmt::print("[DEBUG] Final VRAM dumped to /tmp/vram_final.ppm (frame {})\n",
                 frameCount);
    }
  }

  // ─── Cleanup ──────────────────────────────────────

  // Wait for game thread (with timeout)
  if (gameThread.joinable()) {
    gameFinished.store(true, std::memory_order_release);
    auto deadline = std::chrono::steady_clock::now() + std::chrono::seconds(2);
    while (!gameFinished.load(std::memory_order_acquire) &&
           std::chrono::steady_clock::now() < deadline) {
      std::this_thread::sleep_for(std::chrono::milliseconds(10));
    }
    if (gameThread.joinable()) {
      gameThread.detach(); // Don't block forever
      fmt::print("[Main] Game thread detached (still running)\n");
    }
  }

  // Join vblank ticker (gameFinished is already set above, so it will exit)
  if (vblankThread.joinable())
    vblankThread.join();

  if (audioDevice > 0) {
    SDL_CloseAudioDevice(audioDevice);
  }
  if (gamepad) {
    SDL_GameControllerClose(gamepad);
  }
  renderer.destroy();
  SDL_Quit();

  fmt::print("Simulation ended after {} frames.\n", frameCount);
  return 0;
}
