// ps1xRecomp — PS1 Static Recompiler
// Translates MIPS I instructions to C++ code (1:1 literal translation)

#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fmt/format.h>
#include <fstream>
#include <map>
#include <ps1recomp/elf_parser.h>
#include <ps1recomp/instruction_emitter.h>
#include <ps1recomp/mips_decoder.h>
#include <ps1recomp/overlay_handler.h>
#include <string>
#include <toml.hpp>
#include <vector>

using namespace ps1recomp;

int main(int argc, char *argv[]) {
  if (argc < 2) {
    fmt::print("Usage: ps1xRecomp <config.toml> [output_file.cpp]\n");
    return 1;
  }

  std::string config_path = argv[1];
  std::string output_path = (argc >= 3) ? argv[2] : "recompiled_out.cpp";

  try {
    const auto config = toml::parse(config_path);

    // binary path is relative to the config file ideally, but for now we assume
    // it builds from project root
    std::string elf_path = toml::find<std::string>(config, "binary", "path");
    uint32_t entry_point = std::stoul(
        toml::find<std::string>(config, "binary", "entry_point"), nullptr, 16);

    fmt::print("Loading binary: {}\n", elf_path);
    ps1recomp::ElfParser parser;
    if (!parser.load(elf_path)) {
      fmt::print(stderr, "Failed to load ELF: {}\n", parser.getError());
      return 1;
    }

    std::string result_cpp = "// Generated by ps1xRecomp\n";
    result_cpp += "#include <cstdint>\n";
    result_cpp += "#include <fmt/format.h>\n";
    result_cpp += "#include <runtime/ps1_runtime_macros.h>\n";
    result_cpp += "#include <runtime/cpu_context.h>\n";
    result_cpp += "#include <runtime/gte.h>\n";
    result_cpp += "#include <runtime/bios/bios.h>\n\n";
    result_cpp += "// Forward declaration for OOB dispatch\n";
    result_cpp += "void recomp_dispatch(uint8_t* rdram, recomp_context* ctx, "
                  "uint32_t addr);\n\n";

    const auto &functions =
        toml::find<std::vector<toml::value>>(config, "functions");

    std::map<uint32_t, std::string> addr_to_name;
    std::vector<uint32_t> known_funcs;
    for (const auto &func : functions) {
      std::string name = toml::find<std::string>(func, "name");
      if (name == "main")
        name = "func_main";
      for (char &c : name)
        if (c == '.')
          c = '_';
      uint32_t addr =
          std::stoul(toml::find<std::string>(func, "address"), nullptr, 16);
      known_funcs.push_back(addr);
      addr_to_name[addr] = name;
      result_cpp +=
          fmt::format("void {}(uint8_t* rdram, recomp_context* ctx);\n", name);
    }

    // Also include stubs in known functions if they exist
    if (config.contains("stubs")) {
      const auto &stubs = toml::find<std::vector<toml::value>>(config, "stubs");
      for (const auto &s : stubs) {
        std::string name = toml::find<std::string>(s, "name");
        if (name == "main")
          name = "func_main";
        for (char &c : name)
          if (c == '.')
            c = '_';
        uint32_t addr =
            std::stoul(toml::find<std::string>(s, "address"), nullptr, 16);
        known_funcs.push_back(addr);
        addr_to_name[addr] = name;
        result_cpp += fmt::format(
            "void {}(uint8_t* rdram, recomp_context* ctx);\n", name);
      }
    }

    result_cpp += "\n";

    InstructionEmitter emitter;
    emitter.setFuncResolver([&addr_to_name](uint32_t addr) {
      if (addr_to_name.count(addr))
        return addr_to_name[addr];
      return fmt::format("func_{:08X}", addr);
    });

    fmt::print("Recompiling {} functions...\n", functions.size());

    for (const auto &func : functions) {
      std::string name = toml::find<std::string>(func, "name");
      if (name == "main")
        name = "func_main";
      for (char &c : name)
        if (c == '.')
          c = '_';
      uint32_t addr =
          std::stoul(toml::find<std::string>(func, "address"), nullptr, 16);
      uint32_t size = toml::find<int64_t>(func, "size");

      // Extract instructions
      auto *section = parser.findSectionByAddress(addr);
      if (!section || section->type != SectionType::Text)
        continue;

      uint32_t offset = addr - section->vaddr;
      uint32_t num_instrs = size / 4;

      RecompFunction rfunc;
      rfunc.name = name;
      rfunc.address = addr;
      rfunc.size = size;
      rfunc.instructions.resize(num_instrs);
      rfunc.isLabelTarget.resize(num_instrs, false);

      for (uint32_t i = 0; i < num_instrs; ++i) {
        const uint8_t *ptr = section->data + offset + (i * 4);
        rfunc.instructions[i] =
            ptr[0] | (ptr[1] << 8) | (ptr[2] << 16) | (ptr[3] << 24);

        Instruction inst = MipsDecoder::decode(rfunc.instructions[i]);
        if (inst.category == InstrCategory::Branch) {
          uint32_t pc = addr + (i * 4);
          uint32_t target = inst.branchTarget(pc);
          if (target >= addr && target < addr + size) {
            uint32_t target_idx = (target - addr) / 4;
            if (target_idx < num_instrs)
              rfunc.isLabelTarget[target_idx] = true;
          }
        } else if (inst.category == InstrCategory::Jump &&
                   (inst.id == InstrId::J || inst.id == InstrId::JAL)) {
          uint32_t pc = addr + (i * 4);
          uint32_t target = inst.jumpTarget(pc);
          if (target >= addr && target < addr + size) {
            uint32_t target_idx = (target - addr) / 4;
            if (target_idx < num_instrs)
              rfunc.isLabelTarget[target_idx] = true;
          }
          if (inst.id == InstrId::JAL) {
            bool found = false;
            for (auto k : known_funcs) {
              if (k == target) {
                found = true;
                break;
              }
            }
            if (!found) {
              known_funcs.push_back(target);
              result_cpp += fmt::format(
                  "void func_{:08X}(uint8_t* rdram, recomp_context* ctx) {{ /* "
                  "STUB generated by JAL */ }}\n",
                  target);
            }
          }
        }
      }

      result_cpp += emitter.emitFunction(rfunc);
      result_cpp += "\n";
    }

    // Emit stub implementations for PsyQ stubs!
    if (config.contains("stubs")) {
      const auto &stubs = toml::find<std::vector<toml::value>>(config, "stubs");
      for (const auto &s : stubs) {
        std::string name = toml::find<std::string>(s, "name");
        for (char &c : name)
          if (c == '.')
            c = '_';
        result_cpp += fmt::format("void {}(uint8_t* rdram, recomp_context* "
                                  "ctx) {{ /* PsyQ Stub */ }}\n",
                                  name);
      }
    }

    // ─── Overlay support ──────────────────────────────────
    // Parse [[overlays]] from config. Each overlay is a separate code segment
    // loaded from disc into RAM at a specific address. Functions are prefixed
    // with overlay name to avoid collisions when multiple overlays share RAM.
    OverlayHandler overlayHandler;
    if (config.contains("overlays")) {
      const auto &overlays =
          toml::find<std::vector<toml::value>>(config, "overlays");

      fmt::print("Processing {} overlay(s)...\n", overlays.size());

      for (const auto &ov : overlays) {
        std::string ovl_name = toml::find<std::string>(ov, "name");
        uint32_t ovl_ramBase =
            static_cast<uint32_t>(toml::find<int64_t>(ov, "ram_base"));
        uint32_t ovl_size =
            static_cast<uint32_t>(toml::find<int64_t>(ov, "size"));

        // Load overlay binary data
        std::string ovl_path;
        if (ov.contains("binary_path")) {
          ovl_path = toml::find<std::string>(ov, "binary_path");
        } else if (ov.contains("disc_path")) {
          ovl_path = toml::find<std::string>(ov, "disc_path");
        }

        std::vector<uint8_t> ovl_data;
        uint32_t ovl_codeOffset = 0;
        uint32_t ovl_codeSize = ovl_size;

        if (!ovl_path.empty()) {
          // Resolve path relative to config file directory
          std::filesystem::path cfgDir =
              std::filesystem::path(config_path).parent_path();
          std::filesystem::path fullPath = cfgDir / ovl_path;
          if (!std::filesystem::exists(fullPath))
            fullPath = ovl_path; // try as absolute

          std::ifstream ovlFile(fullPath, std::ios::binary);
          if (ovlFile) {
            ovlFile.seekg(0, std::ios::end);
            auto fileSize = ovlFile.tellg();
            ovlFile.seekg(0, std::ios::beg);
            ovl_data.resize(fileSize);
            ovlFile.read(reinterpret_cast<char *>(ovl_data.data()), fileSize);

            // Check for PS-X EXE header
            if (ovl_data.size() >= 2048 &&
                std::memcmp(ovl_data.data(), "PS-X EXE", 8) == 0) {
              ovl_codeOffset = 2048;
              // Read tAddr/tSize from header
              uint32_t tAddr, tSize;
              std::memcpy(&tAddr, ovl_data.data() + 24, 4);
              std::memcpy(&tSize, ovl_data.data() + 28, 4);
              ovl_ramBase = tAddr; // Use header's own address
              ovl_codeSize = tSize;
              fmt::print("  [{}] PS-X EXE: ram=0x{:08X}, code={}B\n", ovl_name,
                         ovl_ramBase, ovl_codeSize);
            }
          } else {
            fmt::print(stderr, "  Warning: Could not open overlay binary: {}\n",
                       fullPath.string());
            continue;
          }
        }

        // Get function list — from config or scan for prologues
        std::vector<uint32_t> ovl_funcs;
        if (ov.contains("functions")) {
          auto funcs = toml::find<std::vector<int64_t>>(ov, "functions");
          for (auto f : funcs)
            ovl_funcs.push_back(static_cast<uint32_t>(f));
        } else if (!ovl_data.empty() &&
                   ovl_codeOffset + ovl_codeSize <= ovl_data.size()) {
          // Auto-detect function prologues
          const uint8_t *code = ovl_data.data() + ovl_codeOffset;
          size_t codeLen = ovl_codeSize;
          for (size_t i = 0; i + 3 < codeLen; i += 4) {
            uint32_t word = code[i] | (code[i + 1] << 8) |
                            (code[i + 2] << 16) | (code[i + 3] << 24);
            // ADDIU $sp, $sp, -N (stack frame allocation = prologue)
            uint8_t op = (word >> 26) & 0x3F;
            uint8_t rs = (word >> 21) & 0x1F;
            uint8_t rt = (word >> 16) & 0x1F;
            int16_t imm = static_cast<int16_t>(word & 0xFFFF);
            if (op == 0x09 && rs == 29 && rt == 29 && imm < 0) {
              ovl_funcs.push_back(ovl_ramBase + static_cast<uint32_t>(i));
            }
          }
          fmt::print("  [{}] Auto-detected {} functions\n", ovl_name,
                     ovl_funcs.size());
        }

        // Determine function sizes (distance to next function)
        std::sort(ovl_funcs.begin(), ovl_funcs.end());

        // Forward-declare overlay functions
        for (size_t fi = 0; fi < ovl_funcs.size(); ++fi) {
          uint32_t fAddr = ovl_funcs[fi];
          std::string fName =
              fmt::format("overlay_{}__{:08X}", ovl_name, fAddr);
          addr_to_name[fAddr] = fName;
          known_funcs.push_back(fAddr);
          result_cpp += fmt::format(
              "void {}(uint8_t* rdram, recomp_context* ctx);\n", fName);
        }

        // Emit overlay functions
        if (!ovl_data.empty() &&
            ovl_codeOffset + ovl_codeSize <= ovl_data.size()) {
          const uint8_t *code = ovl_data.data() + ovl_codeOffset;

          for (size_t fi = 0; fi < ovl_funcs.size(); ++fi) {
            uint32_t fAddr = ovl_funcs[fi];
            uint32_t fEnd = (fi + 1 < ovl_funcs.size())
                                ? ovl_funcs[fi + 1]
                                : (ovl_ramBase + ovl_codeSize);
            uint32_t fSize = fEnd - fAddr;

            uint32_t localOff = fAddr - ovl_ramBase;
            if (localOff + fSize > ovl_codeSize)
              continue;

            uint32_t numInstrs = fSize / 4;
            RecompFunction rfunc;
            rfunc.name = fmt::format("overlay_{}__{:08X}", ovl_name, fAddr);
            rfunc.address = fAddr;
            rfunc.size = fSize;
            rfunc.instructions.resize(numInstrs);
            rfunc.isLabelTarget.resize(numInstrs, false);

            for (uint32_t ii = 0; ii < numInstrs; ++ii) {
              const uint8_t *ptr = code + localOff + (ii * 4);
              rfunc.instructions[ii] =
                  ptr[0] | (ptr[1] << 8) | (ptr[2] << 16) | (ptr[3] << 24);

              Instruction inst = MipsDecoder::decode(rfunc.instructions[ii]);
              if (inst.category == InstrCategory::Branch) {
                uint32_t pc = fAddr + (ii * 4);
                uint32_t target = inst.branchTarget(pc);
                if (target >= fAddr && target < fAddr + fSize) {
                  uint32_t idx = (target - fAddr) / 4;
                  if (idx < numInstrs)
                    rfunc.isLabelTarget[idx] = true;
                }
              } else if (inst.category == InstrCategory::Jump &&
                         (inst.id == InstrId::J || inst.id == InstrId::JAL)) {
                uint32_t pc = fAddr + (ii * 4);
                uint32_t target = inst.jumpTarget(pc);
                if (target >= fAddr && target < fAddr + fSize) {
                  uint32_t idx = (target - fAddr) / 4;
                  if (idx < numInstrs)
                    rfunc.isLabelTarget[idx] = true;
                }
              }
            }

            result_cpp += emitter.emitFunction(rfunc);
            result_cpp += "\n";
          }
        } else if (ovl_data.empty()) {
          // No binary data — emit stubs for declared functions
          for (auto fAddr : ovl_funcs) {
            std::string fName =
                fmt::format("overlay_{}__{:08X}", ovl_name, fAddr);
            result_cpp +=
                fmt::format("void {}(uint8_t* rdram, recomp_context* ctx) "
                            "{{ /* Overlay stub — no binary data */ }}\n",
                            fName);
          }
        }

        // Register overlay section for tracking
        OverlaySection sec;
        sec.name = ovl_name;
        sec.ramBase = ovl_ramBase;
        sec.size = ovl_codeSize;
        sec.functions = ovl_funcs;
        overlayHandler.addOverlay(std::move(sec));

        fmt::print("  Overlay [{}]: ram=0x{:08X}, size={}, {} functions\n",
                   ovl_name, ovl_ramBase, ovl_codeSize, ovl_funcs.size());
      }
    }

    // ─── Emit overlay table ─────────────────────────────
    // Runtime uses this to know which overlays exist and their address ranges
    if (overlayHandler.overlayCount() > 0) {
      result_cpp += "\n// ─── Overlay Table ──────────────────────────────────\n";
      result_cpp += "#include <vector>\n";
      result_cpp += "#include <string>\n\n";
      result_cpp += "struct OverlayInfo {\n";
      result_cpp += "    std::string name;\n";
      result_cpp += "    uint32_t ramBase;\n";
      result_cpp += "    uint32_t size;\n";
      result_cpp += "    int index;\n";
      result_cpp += "};\n\n";
      result_cpp += "static std::vector<OverlayInfo> recomp_overlay_table = {\n";
      int idx = 0;
      for (const auto &ovl : overlayHandler.overlays()) {
        result_cpp += fmt::format(
            "    {{ \"{}\", 0x{:08X}, {}, {} }},\n", ovl.name, ovl.ramBase,
            ovl.size, idx++);
      }
      result_cpp += "};\n\n";
    }

    // ─── Emit dispatch table ──────────────────────────────
    // This allows CALL_INDIRECT / JUMP_INDIRECT to resolve
    // addresses to recompiled functions at runtime.
    // Uses std::unordered_map for O(1) average-case lookup.
    result_cpp += "\n// ─── Dispatch Table ─────────────────────────────────\n";
    result_cpp += "// Maps PS1 addresses to recompiled function pointers\n";
    result_cpp += "// Populated once at startup, queried on every indirect call/jump\n\n";
    result_cpp += "#include <unordered_map>\n\n";
    result_cpp +=
        "typedef void (*recomp_func_t)(uint8_t*, recomp_context*);\n\n";

    // --- Global dispatch table (unordered_map) ---
    result_cpp += "static std::unordered_map<uint32_t, recomp_func_t> recomp_func_table;\n";
    result_cpp += "static bool recomp_table_ready = false;\n\n";

    // --- Init function: populate the map once ---
    result_cpp += "void recomp_init_dispatch_table() {\n";
    result_cpp += fmt::format("    recomp_func_table.reserve({});\n",
                              addr_to_name.size() + 16);
    for (const auto &[addr, name] : addr_to_name) {
      result_cpp += fmt::format("    recomp_func_table[0x{:08X}] = {};\n", addr, name);
    }
    result_cpp += "    recomp_table_ready = true;\n";
    result_cpp += "}\n\n";

    // --- Lookup function ---
    result_cpp += "recomp_func_t recomp_lookup(uint32_t addr) {\n";
    result_cpp += "    auto it = recomp_func_table.find(addr);\n";
    result_cpp += "    return (it != recomp_func_table.end()) ? it->second : nullptr;\n";
    result_cpp += "}\n\n";

    // --- Main dispatch function ---
    result_cpp += "void recomp_dispatch(uint8_t* rdram, recomp_context* ctx, "
                  "uint32_t addr) {\n";
    result_cpp += "    // Lazy-init on first call\n";
    result_cpp += "    if (!recomp_table_ready) recomp_init_dispatch_table();\n\n";

    // Step 1: NULL pointer guard
    result_cpp += "    // 1. NULL pointer guard\n";
    result_cpp += "    if (addr == 0) {\n";
    result_cpp += "        fmt::print(stderr, \"[DISPATCH] NULL function "
                  "pointer! (RA=0x{:08X})\\n\", ctx->r[31]);\n";
    result_cpp += "        return;\n";
    result_cpp += "    }\n\n";

    // Step 2: Direct lookup
    result_cpp += "    // 2. Direct lookup in dispatch table\n";
    result_cpp += "    recomp_func_t fn = recomp_lookup(addr);\n";
    result_cpp += "    if (fn) { fn(rdram, ctx); return; }\n\n";

    // Step 3: Normalize address (KSEG0/KSEG1 → canonical KSEG0) and retry
    result_cpp += "    // 3. Address normalization (KSEG mirrors) and retry\n";
    result_cpp += "    uint32_t phys = addr & 0x1FFFFFFFu;\n";
    result_cpp += "    uint32_t normalized = phys | 0x80000000u;\n";
    result_cpp += "    if (normalized != addr) {\n";
    result_cpp += "        fn = recomp_lookup(normalized);\n";
    result_cpp += "        if (fn) { fn(rdram, ctx); return; }\n";
    result_cpp += "    }\n\n";

    // Step 4: BIOS entry points A0/B0/C0 (any KSEG mirror)
    result_cpp += "    // 4. BIOS entry points (A0, B0, C0 — any KSEG mirror)\n";
    result_cpp += "    if (ctx->bios) {\n";
    result_cpp += "        if (phys == 0xA0) { ctx->bios->executeA0(); return; }\n";
    result_cpp += "        if (phys == 0xB0) { ctx->bios->executeB0(); return; }\n";
    result_cpp += "        if (phys == 0xC0) { ctx->bios->executeC0(); return; }\n";
    result_cpp += "    }\n\n";

    // Step 5: BIOS table sentinel addresses
    // The BIOS fills B0/C0 tables with sentinel addresses 0x0000B0xx/0x0000C0xx.
    // When the game reads a table entry and jalr's to it, we intercept here.
    result_cpp += "    // 5. BIOS table sentinel dispatch (B0:xx / C0:xx)\n";
    result_cpp += "    if (ctx->bios) {\n";
    result_cpp += "        if (phys >= 0xB000 && phys < 0xB100) {\n";
    result_cpp += "            ctx->r[9] = phys & 0xFF; // set $t1 = function index\n";
    result_cpp += "            ctx->bios->executeB0();\n";
    result_cpp += "            return;\n";
    result_cpp += "        }\n";
    result_cpp += "        if (phys >= 0xC000 && phys < 0xC100) {\n";
    result_cpp += "            ctx->r[9] = phys & 0xFF;\n";
    result_cpp += "            ctx->bios->executeC0();\n";
    result_cpp += "            return;\n";
    result_cpp += "        }\n";
    result_cpp += "        if (phys >= 0xA000 && phys < 0xA100) {\n";
    result_cpp += "            ctx->r[9] = phys & 0xFF;\n";
    result_cpp += "            ctx->bios->executeA0();\n";
    result_cpp += "            return;\n";
    result_cpp += "        }\n";
    result_cpp += "    }\n\n";

    // Step 6: RAM JR-RA trampoline detection
    // BIOS or game may write JR RA (0x03E00008) at hook addresses.
    // If target RAM contains JR RA, the intended behavior is "just return".
    result_cpp += "    // 6. JR RA trampoline detection in RAM\n";
    result_cpp += "    if (phys < 0x200000u) { // Within 2MB main RAM\n";
    result_cpp += "        uint32_t instr = (uint32_t)rdram[phys] | "
                  "((uint32_t)rdram[phys+1] << 8) |\n";
    result_cpp += "                         ((uint32_t)rdram[phys+2] << 16) | "
                  "((uint32_t)rdram[phys+3] << 24);\n";
    result_cpp += "        if (instr == 0x03E00008u) {\n";
    result_cpp += "            return; // JR RA trampoline — no-op return\n";
    result_cpp += "        }\n";
    result_cpp += "    }\n\n";

    // Step 7: Rate-limited fallback logging
    result_cpp += "    // 7. Unknown target — rate-limited log (don't crash)\n";
    result_cpp += "    static std::unordered_map<uint32_t, uint32_t> s_unknownHits;\n";
    result_cpp += "    auto& hitCount = s_unknownHits[addr];\n";
    result_cpp += "    if (hitCount < 5) {\n";
    result_cpp += "        fmt::print(stderr, \"[DISPATCH] Unknown target: "
                  "0x{:08X} (RA=0x{:08X}, phys=0x{:08X})\\n\",\n";
    result_cpp += "                   addr, ctx->r[31], phys);\n";
    result_cpp += "    } else if (hitCount == 5) {\n";
    result_cpp += "        fmt::print(stderr, \"[DISPATCH] Unknown target: "
                  "0x{:08X} — suppressing further logs\\n\", addr);\n";
    result_cpp += "    }\n";
    result_cpp += "    hitCount++;\n";
    result_cpp += "}\n";

    std::ofstream out(output_path);
    if (!out) {
      fmt::print(stderr, "Failed to write output to {}\n", output_path);
      return 1;
    }
    out << result_cpp;
    fmt::print("Success! Emitted Recompiled source to: {}\n", output_path);
    fmt::print("  Dispatch table: {} entries\n", addr_to_name.size());

  } catch (const std::exception &e) {
    fmt::print(stderr, "Error parsing config: {}\n", e.what());
    return 1;
  }

  return 0;
}
